import {useState} from 'react';
import {Search, Download, Plus, Trash2, Server, ShieldCheck, AlertTriangle, ChevronDown, PackageCheck} from 'lucide-react';

type Requirement={name:string,value:string,mandatory:boolean};
type Product={product_id:string;rank:number;product_name:string;manufacturer:string;model?:string;manufacturer_part_number?:string;sku:string;description?:string;technical_specifications:Record<string,string>;unit_price?:number;currency:string;requested_quantity:number;available_quantity?:number;quantity_shortfall?:number;extended_price?:number;warehouse?:string;fulfillment_region?:string;estimated_delivery?:string;warranty?:string;lifecycle_status?:string;confidence_score:number;confidence_level:string;score_breakdown:Record<string,number>;matched_requirements:string[];exceptions:string[];availability_status:string;pricing_timestamp?:string;inventory_timestamp?:string;eligible_countries?:string[];data_source:string};
type Results={recommendations:Product[];regional_verification:Product[];lifecycle_verification:Product[];notice:string;retrieved_at:string};
const countries=['Jamaica','Barbados','Trinidad and Tobago','Bahamas','Dominican Republic','Costa Rica','Panama','Colombia','Mexico','Brazil'];
const categories=['Storage','Servers','Networking','End-user computing','Security','Licensing','Backup'];
const initial:Requirement[]=[{name:'capacity',value:'20TB',mandatory:true},{name:'form factor',value:'3.5-inch',mandatory:true},{name:'interface',value:'SATA',mandatory:true},{name:'speed',value:'7200 RPM',mandatory:true}];
const label=(key:string)=>key.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const shown=(v:unknown)=>v===undefined||v===null||v===''?'Not provided by distributor':String(v);

export default function App(){
 const [form,setForm]=useState({category:'Storage',manufacturer_preference:'',quantity:6,country:'Jamaica',currency:'USD',maximum_unit_price:'',additional_notes:'',allow_exceptions:false});
 const [requirements,setRequirements]=useState(initial); const [results,setResults]=useState<Results|null>(null); const [selected,setSelected]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const [meta,setMeta]=useState({customer_name:'',opportunity_reference:'',prepared_by:'',validity_date:new Date(Date.now()+14*86400000).toISOString().slice(0,10)});
 const updateReq=(i:number,k:keyof Requirement,v:string|boolean)=>setRequirements(r=>r.map((x,n)=>n===i?{...x,[k]:v}:x));
 async function run(){setLoading(true);setError('');setSelected([]);try{const body={...form,maximum_unit_price:form.maximum_unit_price?Number(form.maximum_unit_price):null,requirements};const res=await fetch('/api/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok)throw new Error(res.status===503?'Live API is not configured or unavailable.':'Search could not be completed.');setResults(await res.json())}catch(e){setError(e instanceof Error?e.message:'API unavailable')}finally{setLoading(false)}}
 async function exportQuote(){if(!results||!selected.length||!meta.customer_name||!meta.prepared_by)return;const products=results.recommendations.filter(p=>selected.includes(p.product_id));const body={metadata:{...meta,quote_date:new Date().toISOString().slice(0,10),target_country:form.country,currency:form.currency},products,requirements};const res=await fetch('/api/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok){setError('Quote export failed.');return}const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='product-match-quote.xlsx';a.click();URL.revokeObjectURL(url)}
 return <><header><div className="brand"><div className="mark"><Server size={22}/></div><div><strong>TD SYNNEX</strong><span>Product Matcher</span></div></div><div className="mode"><i/> MOCK MODE</div></header><main>
  <section className="hero"><div><span className="eyebrow">PRE-SALES WORKSPACE</span><h1>Find the right product.<br/><em>Build a defensible quote.</em></h1><p>Match technical requirements against active, regionally eligible products with transparent scoring.</p></div><div className="trust"><ShieldCheck/><div><b>Distributor-safe matching</b><small>Lifecycle, inventory & regional checks applied</small></div></div></section>
  <div className="workspace"><aside><div className="section-head"><div><span>01</span><h2>Customer requirements</h2></div><small>Fields marked mandatory affect compliance.</small></div>
   <label>Product category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label>
   <label>Manufacturer preference <small>Optional</small><input value={form.manufacturer_preference} onChange={e=>setForm({...form,manufacturer_preference:e.target.value})} placeholder="Any manufacturer"/></label>
   <div className="requirements"><div className="req-title"><label>Technical specifications</label><button className="text-btn" onClick={()=>setRequirements([...requirements,{name:'',value:'',mandatory:true}])}><Plus size={14}/> Add</button></div>{requirements.map((r,i)=><div className="req" key={i}><input aria-label="Specification name" value={r.name} onChange={e=>updateReq(i,'name',e.target.value)} placeholder="e.g. capacity"/><input aria-label="Required value" value={r.value} onChange={e=>updateReq(i,'value',e.target.value)} placeholder="e.g. 20TB"/><button aria-label="Remove" onClick={()=>setRequirements(requirements.filter((_,n)=>n!==i))}><Trash2 size={15}/></button><label className="check"><input type="checkbox" checked={r.mandatory} onChange={e=>updateReq(i,'mandatory',e.target.checked)}/> Mandatory</label></div>)}</div>
   <div className="grid"><label>Target country<select value={form.country} onChange={e=>setForm({...form,country:e.target.value})}>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>Currency<select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{['USD','JMD','BBD','TTD','MXN','BRL','COP'].map(x=><option key={x}>{x}</option>)}</select></label><label>Required quantity<input type="number" min="1" value={form.quantity} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/></label><label>Maximum unit price <small>Optional</small><input type="number" min="0" placeholder="No limit" value={form.maximum_unit_price} onChange={e=>setForm({...form,maximum_unit_price:e.target.value})}/></label></div>
   <label>Additional notes <small>Optional</small><textarea placeholder="Intended use, support needs, or other context…" value={form.additional_notes} onChange={e=>setForm({...form,additional_notes:e.target.value})}/></label><label className="exception"><input type="checkbox" checked={form.allow_exceptions} onChange={e=>setForm({...form,allow_exceptions:e.target.checked})}/><span><b>Permit alternatives with mandatory exceptions</b><small>Exceptions will be highlighted and never shown as fully compliant.</small></span></label>
   <button className="primary" onClick={run} disabled={loading}><Search size={18}/>{loading?'Checking catalog…':'Find matching products'}<span>→</span></button>
  </aside><section className="results"><div className="section-head"><div><span>02</span><h2>Recommendations</h2></div>{results&&<small>Retrieved {new Date(results.retrieved_at).toLocaleString()}</small>}</div>
   {!results&&!loading&&!error&&<div className="empty"><div><PackageCheck/></div><h3>Ready to match</h3><p>Enter the customer’s requirements, then search the mock catalog. Up to five verified options will appear here.</p><ul><li>Active & orderable only</li><li>Regional eligibility checked</li><li>Explainable confidence score</li></ul></div>}
   {loading&&<div className="empty"><div className="spinner"/><h3>Checking product eligibility…</h3><p>Validating lifecycle, regional inventory, pricing, and technical compliance.</p></div>}{error&&<div className="state error"><AlertTriangle/> <div><b>API unavailable</b><p>{error}</p></div></div>}
   {results&&results.recommendations.length===0&&<div className="state"><AlertTriangle/><div><b>No matching active products</b><p>No product met the 70% threshold and all mandatory, lifecycle, and regional rules.</p></div></div>}
   {results?.recommendations.map(p=><ProductCard key={p.product_id} p={p} selected={selected.includes(p.product_id)} toggle={()=>setSelected(s=>s.includes(p.product_id)?s.filter(x=>x!==p.product_id):[...s,p.product_id])}/>)}
   {results&&results.regional_verification.length>0&&<details className="verification"><summary><AlertTriangle size={17}/> Regional availability requires confirmation <b>{results.regional_verification.length}</b><ChevronDown/></summary><p>These products are not included in the primary recommendations because eligibility for {form.country} was not confirmed.</p></details>}
   {results&&results.lifecycle_verification.length>0&&<details className="verification"><summary><AlertTriangle size={17}/> Lifecycle status not verified <b>{results.lifecycle_verification.length}</b><ChevronDown/></summary><p>Unknown lifecycle products are excluded until active and orderable status is confirmed.</p></details>}
  </section></div>
  {selected.length>0&&<section className="export"><div><span className="eyebrow">03 QUOTE EXPORT</span><h2>Finish the quote details</h2><p>{selected.length} product{selected.length>1?'s':''} selected · Workbook includes summary, compliance, and full product details.</p></div><div className="meta"><input placeholder="Customer name *" value={meta.customer_name} onChange={e=>setMeta({...meta,customer_name:e.target.value})}/><input placeholder="Opportunity / tender reference" value={meta.opportunity_reference} onChange={e=>setMeta({...meta,opportunity_reference:e.target.value})}/><input placeholder="Prepared by *" value={meta.prepared_by} onChange={e=>setMeta({...meta,prepared_by:e.target.value})}/><label>Valid through<input type="date" value={meta.validity_date} onChange={e=>setMeta({...meta,validity_date:e.target.value})}/></label><button className="primary" disabled={!meta.customer_name||!meta.prepared_by} onClick={exportQuote}><Download size={17}/> Export Excel quote</button></div></section>}
 </main><footer><span>Internal use only · Mock data is synthetic and not a distributor quote.</span><span>Pricing and availability are subject to final confirmation by TD SYNNEX at the time of order.</span></footer></>
}

function ProductCard({p,selected,toggle}:{p:Product;selected:boolean;toggle:()=>void}){const [open,setOpen]=useState(false);return <article className={'product '+(selected?'selected':'')}><div className="product-top"><label className="select"><input type="checkbox" checked={selected} onChange={toggle}/><span/></label><div className="rank">#{p.rank}</div><div className="product-title"><small>{p.manufacturer} · {shown(p.model)}</small><h3>{p.product_name}</h3><p>{p.description}</p></div><div className={'score '+(p.confidence_score>=90?'excellent':'')}><b>{p.confidence_score}%</b><span>{p.confidence_level}</span></div></div><div className="facts"><div><small>UNIT PRICE</small><b>{p.unit_price==null?'Pricing unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:p.currency}).format(p.unit_price)}</b></div><div><small>REQUESTED / AVAILABLE</small><b>{p.requested_quantity} / {shown(p.available_quantity)}</b>{(p.quantity_shortfall??0)>0&&<em>Shortfall: {p.quantity_shortfall}</em>}</div><div><small>EXTENDED PRICE</small><b>{p.extended_price==null?'Not provided':new Intl.NumberFormat('en-US',{style:'currency',currency:p.currency}).format(p.extended_price)}</b></div><div><small>FULFILLMENT</small><b>{shown(p.warehouse)}</b><span>{p.availability_status}</span></div></div><button className="details" onClick={()=>setOpen(!open)}>Technical compliance & score breakdown <ChevronDown className={open?'up':''} size={17}/></button>{open&&<div className="detail-grid"><div><h4>Score breakdown</h4>{Object.entries(p.score_breakdown).map(([k,v])=><div className="bar" key={k}><span>{label(k)}</span><div><i style={{width:`${v/(k==='mandatory_technical_specifications'?50:k==='product_type_and_intended_use'||k==='regional_availability'?15:k==='available_quantity'?10:5)*100}%`}}/></div><b>+{v}</b></div>)}</div><div><h4>Technical specifications</h4><dl>{Object.entries(p.technical_specifications).map(([k,v])=><div key={k}><dt>{label(k)}</dt><dd>{v}</dd></div>)}</dl>{p.exceptions.length>0&&<div className="exceptions"><b>Exceptions / clarification</b>{p.exceptions.map(x=><p key={x}>{x}</p>)}</div>}</div><div className="identifiers"><span>MPN <b>{shown(p.manufacturer_part_number)}</b></span><span>TD SYNNEX SKU <b>{p.sku}</b></span><span>Lifecycle <b>{shown(p.lifecycle_status)}</b></span><span>Warranty <b>{shown(p.warranty)}</b></span><span>Estimated delivery <b>{shown(p.estimated_delivery)}</b></span><span>Last inventory check <b>{p.inventory_timestamp?new Date(p.inventory_timestamp).toLocaleString():'Not provided by distributor'}</b></span></div></div>}</article>}
